version: '3.8'

services:

  ingestor:
    container_name: ingestor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    ports:
      - 8080:8080
      - "12201:12201/udp"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/actuator/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - staging
    networks:
      - shared_network

  ingestor-dev:
    container_name: ingestor-dev
    image: hamidtarmazdi/java-dev:17
    depends_on:
      - influxdb
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
      - "12201:12201/udp"
    env_file:
      - .env
    profiles:
      - dev
    networks:
      - shared_network
    command: sleep infinity

  influxdb:
    image: influxdb:2.7
    volumes:
      - influxdb-data:/var/lib/influxdb2
    env_file:
      - .env
    ports:
      - 8086:8086
    profiles:
      - staging
      - dev
    networks:
      - shared_network

  log-generator:
    container_name: log-generator
    image: hamidtarmazdi/log-generator:1
    depends_on:
      ingestor:
        condition: service_healthy
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
    profiles:
      - staging
    networks:
      - shared_network

volumes:
  influxdb-data:


networks:
  shared_network:
    driver: bridge
