version: '3.8'

services:

  ingestor:
    container_name: ingestor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    ports:
      - 8080:8080
      - "12201:12201/udp"
    environment:
      - GELF_PORT=12201
      - BUFFER_SIZE=1024
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/actuator/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  influxdb:
    image: influxdb:2.7
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    ports:
      - 8086:8086

  log-generator:
    container_name: log-generator
    image: hamidtarmazdi/log-generator:latest
    depends_on:
      ingestor:
        condition: service_healthy
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201

volumes:
  influxdb-data:
